name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
      working-directory: ./build
    - name: make
      run: make all
      working-directory: ./build
    - name: unit-test
      run: ./tst/ExampleProject_tst
      working-directory: ./build
      
